services:
  testapp:
    image: ergrassa/testapp:latest
    environment:
      - MULTIPLIER=4
      - VIRTUAL_HOST=testapp.webapp.zerog.cc
      - LETSENCRYPT_HOST=testapp.webapp.zerog.cc
      - LETSENCRYPT_EMAIL=testapp@zerog.cc
    networks:
      - proxy
networks:
  proxy:
    external: true
